### ISSUE TITLE
Seller Profile - Story

### ISSUE THREAD

**Issue by hol16046** [hol16046/wdd430_group#3]
As a [seller] I want to [be able to share about my business story with potential customers] so that [they can learn more about my craft and connect with my story]. 

Include an 'about me' section in the seller profile that can be updated by the seller.

**Comment by keelw** [comment]
https://business.adobe.com/blog/basics/user-stories-overview#:~:text=A%20user%20story%20is%20a,steps%20that%20are%20more%20manageable.
